name: Run Python Tests

# Define when this workflow should run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest

    # Specify Python versions to test using matrix strategy
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      # 1. Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up the specified Python version
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # 3. Install dependencies
      #    Upgrade pip and install test dependencies from pyproject.toml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]

      # 4. Run tests using pytest
      #    Use pytest-cov to measure test coverage
      - name: Run tests with pytest
        run: |
          pytest --cov=scope_timer tests/

